version: '3.7'

services:
  php:
    build:
      context: ./docker/php
    container_name: peb_php
    volumes:
      - .:/var/www/html:delegated
      - ../../.composer:/var/www/.composer
    working_dir: /var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
#    expose:
#      - 9003
    # x-debug on WSL
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  nginx:
    image: nginx:latest
    container_name: peb_nginx
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default

  mysql:
    image: mysql:latest
    command: 'mysqld --innodb-flush-method=fsync' # --innodb-use-native-aio=0
    restart: unless-stopped
    container_name: peb_mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - default

networks:
  default:
    name: nginx-proxy
    external: true
