services:
  php:
    build:
      context: ./docker/php
    container_name: peb_php
    volumes:
      - .:/var/www/html:delegated
      - ../../.composer:/var/www/.composer
    working_dir: /var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  nginx:
    container_name: peb_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        PHP_UPSTREAM_CONTAINER: ${NGINX_PHP_UPSTREAM_CONTAINER}
        PHP_UPSTREAM_PORT: ${NGINX_PHP_UPSTREAM_PORT}
    environment:
      - VIRTUAL_HOST=${NGINX_HOST}
      - FASTCGI_READ_TIMEOUT=${FASTCGI_READ_TIMEOUT:-60s}
    depends_on:
      - php
    volumes:
      - .:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  mysql:
    image: mysql:latest
    command: 'mysqld --innodb-flush-method=fsync --sort_buffer_size=1M'
    restart: unless-stopped
    container_name: peb_mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - default

networks:
  default:
    name: nginx-proxy
    external: true
