# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    doc_upload_directory: '%kernel.project_dir%/public/storage/doc'
    course_upload_directory: '%kernel.project_dir%/public/storage/course'
    report_upload_directory: '%kernel.project_dir%/public/storage/report'
    exchange_1c_upload_directory: '%kernel.project_dir%/public/storage/exchange1c'
    view_directory: '%kernel.project_dir%/templates'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $courseUploadPath: '%kernel.project_dir%/public/storage/course'
            $reportUploadPath: '%kernel.project_dir%/public/storage/report'
            $exchange1cUploadDirectory: '%kernel.project_dir%/public/storage/exchange1c'
            $avatarUploadPath: '%kernel.project_dir%/public/storage/avatar'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Расширение TWIG для вывода вопросов
    App\TwigExtension\TwigExtension:
        tags:
        - { name: twig.extension }

    # Расширение TWIG для результата тестирования
    App\TwigExtension\HistoryTwigExtension:
        tags:
        - { name: twig.extension }

    # Модификация стандартного логгера для логирования ip адресов
    monolog.processor.web:
        class: Monolog\Processor\WebProcessor
        tags:
        - { name: monolog.processor }

    # Course auto-remove child records
    App\EventListener\CourseRemoveEventListener:
        tags:
            - name: 'doctrine.event_listener'
              event: 'preRemove'

    # Answer auto-remove child records
    App\EventListener\QuestionRemoveEventListener:
        tags:
            - name: 'doctrine.event_listener'
              event: 'preRemove'
    # Permission auto-remove child records
    App\EventListener\PermissionRemoveEventListener:
        tags:
            - { name: 'doctrine.event_listener', event: preRemove }
            - { name: 'doctrine.event_listener', event: prePersist }
    # ModuleSectionPage auto-remove child records
    App\EventListener\ModuleSectionRemoveEventListener:
        tags:
            - name: 'doctrine.event_listener'
              event: 'preRemove'
    # ModuleSection auto-remove child records
    App\EventListener\ModuleRemoveEventListener:
        tags:
            - name: 'doctrine.event_listener'
              event: 'preRemove'
