# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    doc_upload_directory: '%kernel.project_dir%/public/storage/doc'
    course_upload_directory: '%kernel.project_dir%/public/storage/course'
    exchange_1c_upload_directory: '%kernel.project_dir%/public/storage/exchange1c'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $courseUploadPath: '%kernel.project_dir%/public/storage/course'
            $interactiveUploadPath: '%kernel.project_dir%/public/storage/interactive'
            $reportUploadPath: '%kernel.project_dir%/public/storage/report'
            $exchange1cUploadDirectory: '%kernel.project_dir%/public/storage/exchange1c'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Расширение TWIG для вывода вопросов
    App\TwigExtension\TwigExtension:
        tags:
        - { name: twig.extension }
    # Расширение TWIG для результата тестирования
    App\TwigExtension\HistoryTwigExtension:
        tags:
        - { name: twig.extension }

    # Gedmo Timestampable services
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
        - { name: doctrine.event_subscriber, connection: default }
        calls:
        - [ setAnnotationReader, [ "@annotation_reader" ] ]
    
    # Course auto-remove child records
    App\EventListener\CourseRemoveEventListener:
        tags:
            - name: 'doctrine.event_listener'
              event: 'preRemove'
    
    # Answer auto-remove child records
    App\EventListener\QuestionRemoveEventListener:
        tags:
            - name: 'doctrine.event_listener'
              event: 'preRemove'
